### ISSUE TITLE
Incorrect reference to google.maps.Polyline?

### ISSUE THREAD

**Issue by eelcocramer** [StephanGeorg/leaflet-routeboxer#3]
Shouldn't [this line](https://github.com/StephanGeorg/leaflet-routeboxer/blob/master/src/leaflet-routeboxer.js#L89) read:

```
    } else if (path instanceof L.Polyline) {
```

?

**Comment by StephanGeorg** [comment]
Yes, you're right. I fixed it in the master branch.
