### ISSUE TITLE
Error TypeError: Cannot set property '-2' of undefined

### ISSUE THREAD

**Issue by Champirius** [StephanGeorg/leaflet-routeboxer#5]
I have this next example.

var distance = 0.1;
    var route = [
  [50.5, 30.5],
  [50.4, 30.6],
  [50.3, 30.7]
];
var boxes = L.RouteBoxer.box(route, distance);

When I run the example the console display the error.

**Comment by StephanGeorg** [comment]
Ok, will check that. Thanks.

**Comment by StephanGeorg** [comment]
Sry, cannot reproduce the error.
