### ISSUE TITLE
Demo call endup in CORS

### ISSUE THREAD

**Issue by holimatic** [StephanGeorg/leaflet-routeboxer#6]
Dear Stephan,

Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf http://router.project-osrm.org/viaroute?&loc=53.553406,9.992196&loc=48.139126,11.580186&instructions=false&alt=false. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt).(unbekannt)
Object { readyState: 0, getResponseHeader: .ajax/v.getResponseHeader(), getAllResponseHeaders: .ajax/v.getAllResponseHeaders(), setRequestHeader: .ajax/v.setRequestHeader(), overrideMimeType: .ajax/v.overrideMimeType(), statusCode: .ajax/v.statusCode(), abort: .ajax/v.abort(), state: .Deferred/d.state(), always: .Deferred/d.always(), then: .Deferred/d.then(), 11 weitere… }app.js:96:5

This error message I can see in the console. I don't now why? Could you pls. help me or correct this link. The same error message I have if I download all files.

Guido

**Comment by StephanGeorg** [comment]
Hey @holimatic.

This is because 

> The OSRM Demo server has moved to API Version 5.

I will update the demo in a minute ...

**Comment by StephanGeorg** [comment]
Fixed the example! Don't forget that http://router.project-osrm.org is just for testing.
