### ISSUE TITLE
Remove a routebox

### ISSUE THREAD

**Issue by holimatic** [StephanGeorg/leaflet-routeboxer#7]
Dear Stephan,
I was able to successfully integrate a routeboxer into my application. Now I have a question: I'm not able to remove a previously drawn routebox from the map. I could not find any hints in the code. How can I do this?
Any help is appreciated, thanks a lot...
Guido Hollenstein CH

**Comment by StephanGeorg** [comment]
The RouteBoxer returns a set of L.LatLngBounds. 

> I'm not able to remove a previously drawn routebox from the map.

Please checkout the Leaflet documentation http://leafletjs.com/reference.html
