### ISSUE TITLE
Using mapbox router

### ISSUE THREAD

**Issue by holimatic** [StephanGeorg/leaflet-routeboxer#8]
Hi Stephan,

Can I use mapbox router instead of osrm router? If yes, do you have an example?

Guido

**Comment by StephanGeorg** [comment]
Hi Guido. 

Sure you can. Did you try to replace the OSRM endpoint with the one from Mapbox? As I see in the [API documentation](https://api.mapbox.com/directions/v5/mapbox/driving/) it should be compatible with OSRM. So try to replace 

`var url = 'https://router.project-osrm.org/route/v1/driving/';`

with the one from Mapbox

`var url = 'https://api.mapbox.com/directions/v5/mapbox/driving/';`

and add your access token to the data object:

`data: {
      overview: 'full',
      access_token: 'your-access-token-from-mapbox'
    },
    dataType: 'json'`

Didn't try it but this should work.

**Comment by holimatic** [comment]
Hi Stephan,

Yes, that works perfectly thanks a lot...
